#!/bin/bash

if (( $# != 2 )); then
    echo "Usage: pupexplode <pup> <out_dir>"
    echo "pupexplode expands all important files in a PUP and tries to decrypt every file as a self"
    exit 1
fi

pup=$1
outdir=$2

pupunpack $pup $outdir || exit

cd $outdir || exit

mkdir update_files
cd update_files
tar xvf ../update_files.tar || exit
rm ../update_files.tar

for f in dev_flash*; do
    unpkg $f ${f}_unpkg || exit
    rm $f
    tar xvf ${f}_unpkg/content || exit
    rm -rf ${f}_unpkg
done

for f in *.pkg; do
    unpkg $f ${f%.pkg}
    if [[ $f == "CORE_OS_PACKAGE.pkg" ]]; then
        cosunpkg CORE_OS_PACKAGE/content CORE_OS_PACKAGE/
        rm CORE_OS_PACKAGE/content
    fi
    rm $f
done

find $2 -type f -exec sh -c "echo {}; unself {} {}.dec" \;
