#!/usr/bin/env ksh

if (( $# != 2 )); then
    print "Usage: pupexplode <pup> <out_dir>"
    print "pupexplode expands all important files in a PUP and tries to decrypt every file as a self"
    exit 1
fi

pup=$1
outdir=$2

pupunpack $pup $outdir || exit

cd $outdir || exit

mkdir update_files
cd update_files
tar xvf ../update_files.tar || exit
rm ../update_files.tar

for f in dev_flash*; do
    unpkg $f ${f}_unpkg || exit
    rm $f
    tar xvf ${f}_unpkg/content || exit
    rm -rf ${f}_unpkg
done

for f in *.pkg; do
    unpkg $f ${f%.pkg}
    if [[ $f == "CORE_OS_PACKAGE.pkg" ]]; then
        cosunpkg CORE_OS_PACKAGE/content CORE_OS_PACKAGE/
        rm CORE_OS_PACKAGE/content
    fi
    rm $f
done

cd ..
for f in $(find -type f -print0); do
    if readself $f &> /dev/null; then
        print -n "Unselfing $f... "
        if unself $f ${f}.elf &> /dev/null; then
            print "OK!"
            rm $f
        else
            print "failed!"
        fi
    fi
done

